Adicion de contexto y cambios en el automerge

diff --git a/.github/workflows/HotfixDeployement.yml b/.github/workflows/HotfixDeployement.yml
--- a/.github/workflows/HotfixDeployement.yml
+++ b/.github/workflows/HotfixDeployement.yml
@@ -13,14 +13,17 @@ jobs:
       GITHUB_TOKEN: ${{ secrets.DEPLOY_GH_TOKEN }}
 
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
       - name: Create PR from main to stage
         run: |
           gh pr create --base stage --head main --title "Propagate hotfix to stage" --body "This PR propagates the hotfix from main to stage." --repo ${{ github.repository }} --label "hotfix_propagation" || echo "PR already exists"
           echo "Merging PR number $(gh pr list --base stage --head main --json number -q '.[0].number')"
-          gh pr merge $(gh pr list --base stage --head main --json number -q '.[0].number') -R ${{ github.repository }} --merge --auto || echo "PR already merged or not found"
+          gh pr merge $(gh pr list --base stage --head main --json number -q '.[0].number') --repo ${{ github.repository }} --merge --auto || echo "PR already merged or not found"
       
       - name: Create PR from main to develop
         run: |
           gh pr create --base develop --head main --title "Propagate hotfix to develop" --body "This PR propagates the hotfix from main to develop." --repo ${{ github.repository }} --label "hotfix_propagation" || echo "PR already exists"
           echo "Merging PR number $(gh pr list --base develop --head main --json number -q '.[0].number')"
-          gh pr merge $(gh pr list --base develop --head main --json number -q '.[0].number') -R ${{ github.repository }} --merge --auto || echo "PR already merged or not found"
+          gh pr merge $(gh pr list --base develop --head main --json number -q '.[0].number') --repo ${{ github.repository }} --merge --auto || echo "PR already merged or not found"
