Reintento con el flag de admin y el bypass rule

diff --git a/.github/workflows/HotfixDeployement.yml b/.github/workflows/HotfixDeployement.yml
--- a/.github/workflows/HotfixDeployement.yml
+++ b/.github/workflows/HotfixDeployement.yml
@@ -16,12 +16,12 @@ jobs:
       - name: Create PR from main to stage
         run: |
           gh pr create --base stage --head main --title "Propagate hotfix to stage" --body "This PR propagates the hotfix from main to stage." --repo ${{ github.repository }} --label "hotfix_propagation" || echo "PR already exists"
-          gh pr merge --merge --auto $(gh pr list --base stage --head main --json number -q '.[0].number') --repo ${{ github.repository }} || echo "PR already merged or not found"
+          gh pr merge --merge --admin --auto $(gh pr list --base stage --head main --json number -q '.[0].number') --repo ${{ github.repository }} || echo "PR already merged or not found"
       
       - name: Create PR from main to develop
         run: |
           gh pr create --base develop --head main --title "Propagate hotfix to develop" --body "This PR propagates the hotfix from main to develop." --repo ${{ github.repository }} --label "hotfix_propagation" || echo "PR already exists"
-          gh pr merge --merge --auto $(gh pr list --base develop --head main --json number -q '.[0].number') --repo ${{ github.repository }} || echo "PR already merged or not found"
+          gh pr merge --merge --admin --auto $(gh pr list --base develop --head main --json number -q '.[0].number') --repo ${{ github.repository }} || echo "PR already merged or not found"
 
   check-branch-name:
     runs-on: ubuntu-latest
